/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;
import model.CarDetails;
import model.CarHistory;

/**
 *
 * @author Vini
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    CarHistory history;
    public CreatePanel(CarHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarDtls = new javax.swing.JLabel();
        lblCarName = new javax.swing.JLabel();
        lblCertificate = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblDateManufactured = new javax.swing.JLabel();
        lblMaxNoSeats = new javax.swing.JLabel();
        lblSerialNo = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        txtManufact = new javax.swing.JTextField();
        txtManufacDate = new javax.swing.JTextField();
        txtNumSeats = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        btnAddCar = new javax.swing.JButton();
        lblAvail = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBoxCerti = new javax.swing.JComboBox<>();

        lblCarDtls.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCarDtls.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarDtls.setText("Add Car Details");

        lblCarName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCarName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCarName.setText("Car Name");

        lblCertificate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCertificate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCertificate.setText("Certificate Expired");

        lblManufacturer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblManufacturer.setText("Manufacturer");

        lblDateManufactured.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDateManufactured.setText("Year of Manufactured");

        lblMaxNoSeats.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaxNoSeats.setText("No of Seats");

        lblSerialNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSerialNo.setText("Serial Number");

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCity.setText("City");

        txtCarName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarNameKeyPressed(evt);
            }
        });

        txtManufact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtManufactKeyPressed(evt);
            }
        });

        txtSerialNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerialNoKeyTyped(evt);
            }
        });

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCityKeyTyped(evt);
            }
        });

        btnAddCar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddCar.setText("ADD CAR");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        lblAvail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAvail.setText("Availibility");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Booked" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBoxCerti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxCerti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarDtls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCarName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblManufacturer)
                                    .addComponent(lblCertificate)
                                    .addComponent(lblDateManufactured)
                                    .addComponent(lblMaxNoSeats)
                                    .addComponent(lblSerialNo)
                                    .addComponent(lblCity)
                                    .addComponent(lblAvail))))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCarName)
                                .addComponent(txtManufact)
                                .addComponent(txtManufacDate)
                                .addComponent(txtNumSeats)
                                .addComponent(txtSerialNo)
                                .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCerti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(btnAddCar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblCarDtls)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarName)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer)
                    .addComponent(txtManufact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateManufactured)
                    .addComponent(txtManufacDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxNoSeats)
                    .addComponent(txtNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNo)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertificate)
                    .addComponent(jComboBoxCerti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvail)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnAddCar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        // TODO add your handling code here:
        if(txtCarName.getText().trim().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Must have Car Name");
        txtCarName.setVisible(true);
    }
         
          if(txtManufact.getText().trim().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Must have Manufacturer's name");
        txtManufact.setVisible(true);
    }
           if(txtManufacDate.getText().trim().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Must have year of manufactured");
        txtManufacDate.setVisible(true);
    }
            if(txtNumSeats.getText().trim().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Must have no of seats");
        txtNumSeats.setVisible(true);
    }
            if(txtSerialNo.getText().trim().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Must have serial number");
        txtSerialNo.setVisible(true);
    }
            if(txtCity.getText().trim().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Must have city");
        txtCity.setVisible(true);
    }
        String carName = txtCarName.getText();
        String Certificate = jComboBoxCerti.getSelectedItem().toString();
        String Manufacturer = txtManufact.getText();
        String manufacturedDate = txtManufacDate.getText();;
        int maxSeats =(Integer.valueOf( txtNumSeats.getText()));
        int serialNo = (Integer.valueOf(txtSerialNo.getText()));
        String city =(txtCity.getText());
        String Avail = jComboBox1.getSelectedItem().toString();
        
    CarDetails cd = history.addViewDetails();
    cd.setCity(city);
    cd.setCarName(carName);
    cd.setCertificate(Certificate);
    cd.setManufacturedDate(manufacturedDate);
    cd.setManufacturer(Manufacturer);
    cd.setMaxSeats(maxSeats);
    cd.setSerialNo(serialNo);
    cd.setAvail(Avail);
        JOptionPane.showMessageDialog((this), "Car Details Added");
        
        txtCity.setText("");
        txtCarName.setText("");
        txtManufacDate.setText("");
        txtManufact.setText("");
        txtNumSeats.setText("");
        txtSerialNo.setText("");
      
    }//GEN-LAST:event_btnAddCarActionPerformed

    private void txtCarNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarNameKeyPressed
        char aphabets =evt.getKeyChar();
        if(Character.isLetter(aphabets)||Character.isWhitespace(aphabets)||Character.isISOControl(aphabets)){
            txtCarName.setEditable(true);
        }
        else{
            txtCarName.setEditable(false);
        }    }//GEN-LAST:event_txtCarNameKeyPressed

    private void txtManufactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManufactKeyPressed
        // TODO add your handling code here:
        char aphabets =evt.getKeyChar();
        if(Character.isLetter(aphabets)||Character.isWhitespace(aphabets)||Character.isISOControl(aphabets)){
            txtManufact.setEditable(true);
        }
        else{
            txtManufact.setEditable(false);
        }
    }//GEN-LAST:event_txtManufactKeyPressed

    private void txtSerialNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNoKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
             txtSerialNo.setEditable(true);
        }
    }//GEN-LAST:event_txtSerialNoKeyTyped

    private void txtCityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyTyped
        // TODO add your handling code here:
        char aphabets =evt.getKeyChar();
        if(Character.isLetter(aphabets)||Character.isWhitespace(aphabets)||Character.isISOControl(aphabets)){
            txtCity.setEditable(true);
        }
        else{
            txtCity.setEditable(false);
        }
    }//GEN-LAST:event_txtCityKeyTyped

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxCerti;
    private javax.swing.JLabel lblAvail;
    private javax.swing.JLabel lblCarDtls;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCertificate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDateManufactured;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblMaxNoSeats;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufacDate;
    private javax.swing.JTextField txtManufact;
    private javax.swing.JTextField txtNumSeats;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables
}
